from django.db import models
from django .utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# python manage.py sqlmigrate blog 0001 (0001 is the id)
# this command is used to see the sql code
# the sql code is generated by the ORM(object relational mapper)

#In [1]: from blog.models import Post
#In [2]: from django.contrib.auth.models import User
# write these in the shell

class Post(models.Model):
    title=models.CharField(max_length=100)
    content=models.TextField()
    date=models.DateTimeField(default=timezone.now)
    author=models.ForeignKey(User,on_delete=models.CASCADE)#if a user is deleted the post is also deleted
    
    def __str__(self):  #dunder str method
        return self.title
    
    def get_absolute_url(self):
        return reverse("post-detail",kwargs={'pk':self.pk})
    